volumes:
  postgres:


services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
